# Generated by Django 5.2.8 on 2025-11-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='public',
            field=models.BooleanField(),
        ),
    ]
