# Generated by Django 5.2.8 on 2025-11-23 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_repository_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='repo_collaborator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repository',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['repo_name', 'owner'], name='api_reposit_repo_na_e90c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['user', 'hash'], name='api_token_user_id_764148_idx'),
        ),
    ]
