# Generated by Django 5.2.8 on 2025-11-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_repository_collaborators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='description',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
