services:
  backend:
    build: ./django
    volumes:
      - git-data:/srv/git
    ports:
      - "8000:8000"
    networks:
      - app-network
    env_file:
      - ./django/backend/.env
  git-http:
    build: ./git-server/http/
    volumes:
      - git-data:/srv/git
    ports:
      - "8080:80"
    networks:
      - app-network

  git-ssh:
    build: ./git-server/ssh/ 
    volumes:
      - git-data:/srv/git
    ports:
      - "2222:22"
    networks:
      - app-network

  frontend:
    build:
      context: ./svelte
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./svelte/frontend:/frontend
      - /frontend/node_modules
    command: ["npm", "run", "dev", "--", "--host", "--port", "5173"]
    networks:
      - app-network

volumes:
  git-data:

networks:
  app-network:
    driver: bridge
