server {
  listen 80;
  server_name _;

  #see: https://nginx.org/en/docs/http/ngx_http_auth_request_module.html#auth_request
  #and: https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header
  location = /auth {
      internal;
      proxy_pass http://backend:8000/api/auth/git/;
      proxy_pass_request_body off;
      proxy_set_header Content-Length "";
      proxy_set_header X-Original-URI $request_uri;
      proxy_set_header X-Original-Method $request_method;
      proxy_set_header Authorization $http_authorization;
      proxy_set_header Host $host;
  }

  #regex for git location
  location ~ ^/git(/.*){
      #auth before pushing
      auth_request /auth;
      auth_request_set $auth_www $upstream_http_www_authenticate;
      add_header WWW-Authenticate $auth_www always;
      auth_request_set $user $upstream_http_x_user;

      #using fastcgi for common gateway -- nginx doesn't provide one
      fastcgi_param GIT_HTTP_EXPORT_ALL "";
      include fastcgi_params;
      fastcgi_param GIT_PROJECT_ROOT /srv/git;
      #takes in regex path 
      fastcgi_param PATH_INFO $1;
      fastcgi_param REMOTE_USER $user;
      fastcgi_param SCRIPT_FILENAME /usr/lib/git-core/git-http-backend;
      fastcgi_param HTTP_AUTHORIZATION $http_authorization;
      fastcgi_pass unix:/var/run/fcgiwrap.socket;
  }

}
